### ISSUE TITLE
Meter shows the strongest label when the EditText is first focused on, but with the correct weakest color

### ISSUE THREAD

**Issue by ahhmino** [gustavaa/AndroidPasswordStrengthMeter#2]
Seems to be a small bug when a textfield is first tapped on, it shows the correct color set but with the label for the strongest setting. After typing something in the field then erasing all the text, it shows the correct color + strength label, so this seems to only be an issue on first focus.

**Code:**

```     
val passwordMeter: PasswordStrengthMeter = view.findViewById(R.id.create_account_password_meter)
passwordMeter.setEditText(passwordField)
passwordMeter.setStrengthLevels(
    arrayOf(
        PasswordStrengthLevel("Weak", android.R.color.darker_gray),
        PasswordStrengthLevel("Fair", android.R.color.holo_red_light),
        PasswordStrengthLevel("Good", android.R.color.holo_orange_light),
        PasswordStrengthLevel("Strong", android.R.color.holo_green_light),
        PasswordStrengthLevel("Very Strong", android.R.color.holo_green_dark)
    )
)
```

**Screenshots:**

On first focus:
![image](https://user-images.githubusercontent.com/38871201/107130343-ecf5a400-6891-11eb-85fd-2a01958148c5.png)

After typing and erasing:
![image](https://user-images.githubusercontent.com/38871201/107130339-e1a27880-6891-11eb-8ae3-5b2339ef3123.png)

Feel free to let me know if I missed something though

**Comment by gustavaa** [comment]
Hello @ahhmino and thank you for reporting this issue! The reason for the issue was that the label is not refreshed after calling ```setStrengthLevels```. So if you call ```setEditText```after ```setStrengthLevels```it should work for you.

I have pushed a fix for this, however, it seems that JCenter will close down soon and I have to look at other hosting options, so it will probably take a few days to publish the new version. But I will notify you here when it is updated.

**Comment by ahhmino** [comment]
Thanks for this library! I got it to work after I downloaded your fix - looks like I have to keep the ```setEditText``` before ```setStrengthLevels``` with the new addition of the ```refresh```, and it's working great

**Comment by gustavaa** [comment]
Glad to hear it's working for you!
